## create("thesisR") not needed no more

devtools::use_package("psych")
## devtools::use_testthat()
devtools::use_package(c("plyr"))
devtools::use_package(c("ggplot2"))
devtools::use_package(c("reshape2"))
devtools::use_package(c("GPArotation"))
devtools::use_package(c("xtable"))
devtools::use_package(c("caret"))
devtools::use_package(c("car"))
devtools::use_package(c("glmnet"))
devtools::use_package(c("ltm"))
devtools::use_package("bcv", "Suggests")
devtools::use_package("OpenMx")
devtools::document()
devtools::build()
devtools::lint()
devtools::test()
devtools::check()
devtools::install()
